version: "3"

services:
  database:
    container_name: ${COMPOSE_PROJECT_NAME}_${POSTGRES_SERVER_NAME}
    image: "postgres:latest"
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
  ts-node-docker:
    depends_on:
      - database
    container_name: ${COMPOSE_PROJECT_NAME}_${NODEJS_SERVER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      PGUSER: ${POSTGRES_USER}
      PGHOST: ${POSTGRES_HOST}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGDATABASE: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - "${NODEJS_PORT}"
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
    command: npm run dev
